using Pkg

Pkg.add("Revise")
Pkg.add(PackageSpec(name="StatFiles", version="0.8.0"))
Pkg.add(PackageSpec(name="StatsPlots", version="0.15.7"))
Pkg.add(PackageSpec(name="Optim", version="1.9.4"))
Pkg.add(PackageSpec(name="Distributions", version="0.25.112"))
Pkg.add("Statistics")
Pkg.add(PackageSpec(name="GLM", version="1.9.0"))
Pkg.add(PackageSpec(name="DataFrames", version="1.3.6"))
Pkg.add(PackageSpec(name="Plots", version="1.40.8"))
Pkg.add(PackageSpec(name="LaTeXTabulars", version="1.0.0"))
Pkg.add(PackageSpec(name="LaTeXStrings", version="1.4.0"))
Pkg.add(PackageSpec(name="FixedEffectModels", version="1.11.0"))
Pkg.add("RCall")
Pkg.add(PackageSpec(name="Roots", version="2.2.5"))
